#
# Samantha Foley
# CS 441/541: Project 1 Given Tests
#

check: stdinput banner_help \
	check-python

banner_help:
	@echo "By default check will run all levels."
	@sleep 1

check-python:
	@python given-tests/tester-list.py  given-tests/test-list-stdinput
