#!/bin/bash
trap "exit" INT

sed  -e 's/FRAME/01/g' Noise.rib | sed -e 's/SCALE/0.1/g' | prman
sed  -e 's/FRAME/02/g' Noise.rib | sed -e 's/SCALE/0.2/g' | prman
sed  -e 's/FRAME/03/g' Noise.rib | sed -e 's/SCALE/0.3/g' | prman
sed  -e 's/FRAME/04/g' Noise.rib | sed -e 's/SCALE/0.4/g' | prman
sed  -e 's/FRAME/05/g' Noise.rib | sed -e 's/SCALE/0.5/g' | prman
sed  -e 's/FRAME/06/g' Noise.rib | sed -e 's/SCALE/0.6/g' | prman
sed  -e 's/FRAME/07/g' Noise.rib | sed -e 's/SCALE/0.7/g' | prman
sed  -e 's/FRAME/08/g' Noise.rib | sed -e 's/SCALE/0.8/g' | prman
sed  -e 's/FRAME/09/g' Noise.rib | sed -e 's/SCALE/0.9/g' | prman
sed  -e 's/FRAME/10/g' Noise.rib | sed -e 's/SCALE/1.0/g' | prman
sed  -e 's/FRAME/11/g' Noise.rib | sed -e 's/SCALE/1.1/g' | prman
sed  -e 's/FRAME/12/g' Noise.rib | sed -e 's/SCALE/1.2/g' | prman
sed  -e 's/FRAME/13/g' Noise.rib | sed -e 's/SCALE/1.3/g' | prman
sed  -e 's/FRAME/14/g' Noise.rib | sed -e 's/SCALE/1.4/g' | prman
sed  -e 's/FRAME/15/g' Noise.rib | sed -e 's/SCALE/1.5/g' | prman
sed  -e 's/FRAME/16/g' Noise.rib | sed -e 's/SCALE/1.6/g' | prman
sed  -e 's/FRAME/17/g' Noise.rib | sed -e 's/SCALE/1.7/g' | prman
sed  -e 's/FRAME/18/g' Noise.rib | sed -e 's/SCALE/1.8/g' | prman
sed  -e 's/FRAME/19/g' Noise.rib | sed -e 's/SCALE/1.9/g' | prman
sed  -e 's/FRAME/20/g' Noise.rib | sed -e 's/SCALE/2.0/g' | prman
sed  -e 's/FRAME/21/g' Noise.rib | sed -e 's/SCALE/2.1/g' | prman
sed  -e 's/FRAME/22/g' Noise.rib | sed -e 's/SCALE/2.2/g' | prman
sed  -e 's/FRAME/23/g' Noise.rib | sed -e 's/SCALE/2.3/g' | prman
sed  -e 's/FRAME/24/g' Noise.rib | sed -e 's/SCALE/2.4/g' | prman
sed  -e 's/FRAME/25/g' Noise.rib | sed -e 's/SCALE/2.5/g' | prman
sed  -e 's/FRAME/26/g' Noise.rib | sed -e 's/SCALE/2.6/g' | prman
sed  -e 's/FRAME/27/g' Noise.rib | sed -e 's/SCALE/2.7/g' | prman
sed  -e 's/FRAME/28/g' Noise.rib | sed -e 's/SCALE/2.8/g' | prman
sed  -e 's/FRAME/29/g' Noise.rib | sed -e 's/SCALE/2.9/g' | prman
sed  -e 's/FRAME/30/g' Noise.rib | sed -e 's/SCALE/3.0/g' | prman
sed  -e 's/FRAME/31/g' Noise.rib | sed -e 's/SCALE/3.1/g' | prman
sed  -e 's/FRAME/32/g' Noise.rib | sed -e 's/SCALE/3.2/g' | prman
sed  -e 's/FRAME/33/g' Noise.rib | sed -e 's/SCALE/3.3/g' | prman
sed  -e 's/FRAME/34/g' Noise.rib | sed -e 's/SCALE/3.4/g' | prman
sed  -e 's/FRAME/35/g' Noise.rib | sed -e 's/SCALE/3.5/g' | prman
sed  -e 's/FRAME/36/g' Noise.rib | sed -e 's/SCALE/3.6/g' | prman
sed  -e 's/FRAME/37/g' Noise.rib | sed -e 's/SCALE/3.7/g' | prman
sed  -e 's/FRAME/38/g' Noise.rib | sed -e 's/SCALE/3.8/g' | prman
sed  -e 's/FRAME/39/g' Noise.rib | sed -e 's/SCALE/3.9/g' | prman
sed  -e 's/FRAME/40/g' Noise.rib | sed -e 's/SCALE/4.0/g' | prman
sed  -e 's/FRAME/41/g' Noise.rib | sed -e 's/SCALE/4.1/g' | prman
sed  -e 's/FRAME/42/g' Noise.rib | sed -e 's/SCALE/4.2/g' | prman
sed  -e 's/FRAME/43/g' Noise.rib | sed -e 's/SCALE/4.3/g' | prman
sed  -e 's/FRAME/44/g' Noise.rib | sed -e 's/SCALE/4.4/g' | prman
sed  -e 's/FRAME/45/g' Noise.rib | sed -e 's/SCALE/4.5/g' | prman
sed  -e 's/FRAME/46/g' Noise.rib | sed -e 's/SCALE/4.6/g' | prman
sed  -e 's/FRAME/47/g' Noise.rib | sed -e 's/SCALE/4.7/g' | prman
sed  -e 's/FRAME/48/g' Noise.rib | sed -e 's/SCALE/4.8/g' | prman
sed  -e 's/FRAME/49/g' Noise.rib | sed -e 's/SCALE/4.9/g' | prman
sed  -e 's/FRAME/50/g' Noise.rib | sed -e 's/SCALE/5.0/g' | prman
